using UnityEngine;

namespace Pcb
{
    /// <summary>A point the spark stops at. Its 3D look is generated by the Board.</summary>
    public class PcbNode : MonoBehaviour
    {
        public NodeType type = NodeType.Capacitor;
        [Tooltip("Side this node sits on. Ignored for vias, which go through the board.")]
        public PcbLayer layer = PcbLayer.Front;
        [Tooltip("Goal only: chip size in world units.")]
        public Vector2 chipSize = new Vector2(1f, 1.5f);
        [Tooltip("Spin of the model around the board normal, in degrees. Visual only: trace directions are unaffected.")]
        public float rotationDegrees = 0f;
        [Tooltip("Optional: this node's own model (Level Editor > Paint). Empty = the level's default for this type (Board > Look), then the theme's.")]
        public GameObject model;

        public bool IsVia => type == NodeType.Via;
        public bool IsSwitch => type == NodeType.Switch || type == NodeType.AndSwitch;
        public bool IsOnLayer(PcbLayer l) => IsVia || layer == l;
    }
}
